# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c28e6d8be9d4b2ccc120c77c97885130729b00975aabc85ab1676051bdf84adc2f40372b6553f64f8452ecc566d2f4b48c0c9375599b04325eb3d8595d5f13c0

test:
  secret_key_base: 45860e88502fdb56336269cbfc74ef0625119297aa59b71ed81b481e97ee337894470ba02ebe93726f8981a89c1651969651fd44a85bc4d7f69fc80b1194f1f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 47fc480643aa553bd38cdb694eab1a66b2181e14bef66d6c8838a782fddb47d5097f116d3ff0cde8291efbc64c20b0519a98f8267f21eaacd94e7b989539ad2e
